performance_budget.performance_budget.*:
  type: config_entity
  label: 'Performance Budget config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    schedule:
      type: string
      label: 'Schedule'
